### ISSUE TITLE
No symbol map support for dol files?

### ISSUE THREAD

**Issue by Zephiles** [Cuyler36/Ghidra-GameCube-Loader#1]
When loading a dol file, there are no options to load a symbol map for it. Is this a bug, or something that has not been implemented yet? I am testing this with the dol file for Paper Mario: The Thousand-Year Door, in which there is a symbol map for it.

**Comment by Cuyler36** [comment]
Symbol maps are set to be loaded automatically by default. If the loader finds an exact file name match as the binary it is loading, it will try to load it. If it fails to find a match, it'll ask you if you'd like to manually select a symbol map.

You can disable this option when loading the binary under the options menu. Does the issue still occur if you disable it?

**Comment by Zephiles** [comment]
Yes, this issue still occurs when that option is disabled.

**Comment by Cuyler36** [comment]
This should be resolved now. The issue was caused by an error thrown during uninitialized section creation. My assumption that all sections in the dol header would be in the same index was wrong.
