### ISSUE TITLE
Building Error

### ISSUE THREAD

**Issue by VegaASM** [Cuyler36/Ghidra-GameCube-Loader#13]
OS - Debian 10
Gradle Version - 4.4.1
OpenJDK 11

`I cannot get the build to work. I get the following error-
* What went wrong:
A problem occurred evaluating settings 'glide-master'.
> Process 'command 'git'' finished with non-zero exit value 128

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log `

I have also tried manually installing and using Gradle 5.5.1, still won't work. I have never had issues building the older version (1.0.0). My apologies if this is a simple fix.

**EDIT** Got it to build, but I do not see the zip file or a /dist directory anywhere.

**Comment by Cuyler36** [comment]
I'll have to look into this on a Linux distro when I have the chance. It might have to do with the recent commit addressing the missing gradle build files.

**Comment by Cuyler36** [comment]
I'm going to guess this was a one-time thing. No one else has reported this issue building. LMK if the issue persists.
