### ISSUE TITLE
Build problems on Arch Linux

### ISSUE THREAD

**Issue by RenaKunisaki** [Cuyler36/Ghidra-GameCube-Loader#15]
When running `gradlew` (which wasn't marked executable) I got error:

```
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
Caused by: java.lang.ClassNotFoundException: org.gradle.wrapper.GradleWrapperMain
```

To fix this I had to first run:

```sh
TERM=xterm-color JAVA_HOME=/usr/lib/jvm/java-11-openjdk/ GHIDRA_INSTALL_DIR=/opt/ghidra gradle wrapper
```

Then `gradlew` would execute OK. (The `TERM` setting avoids another error about not getting termcap in gradle.)

**Comment by Cuyler36** [comment]
Interesting. The gradle script won't run without you first setting variables in your environment path. https://github.com/Cuyler36/Ghidra-GameCube-Loader#building

Were those already set before you ran the additional commands?

**Comment by RenaKunisaki** [comment]
I have Android Studio installed, so they were probably set by that.

**Comment by Cuyler36** [comment]
It looks like that's not the case according to the minimal Google searching I did. There's a setting for the JDK path in Android Studio, so it doesn't use/set your JAVA_HOME path. GHIDRA_INSTALL_DIR must also be set which Android Studio most certainly does not do. Here's a guide on how to add those variables to your environment path so you don't have to type them in every time you want to build:
https://wiki.archlinux.org/index.php/Environment_variables#Defining_variables

I'm closing this issue -- if adding those to your environment variables doesn't fix the build issues then I'll reopen.
