### ISSUE TITLE
Gradle Wrapper not working

### ISSUE THREAD

**Issue by Justin113D** [Cuyler36/Ghidra-GameCube-Loader#16]
When running `./gradlew` the error message "Main class org.gradle.wrapper.GradleWrapperMain couldnt be found or loaded, cause: java.lang.ClassNotFoundException: org.gradle.wrapper.GradleWrapperMain" gets thrown

**Comment by wrongbaud** [comment]
Could possibly be something similar to this issue?
https://stackoverflow.com/questions/29805622/could-not-find-or-load-main-class-org-gradle-wrapper-gradlewrappermain/29806323

**Comment by Justin113D** [comment]
thanks for the help! i didnt even know i needed to do this (never worked or even heard of gradle before, as im no java dev), but it seems that the project is not compatible with the newest version of gradle. When running `gradle wrapper` in the repository folder, it says `Process 'command git'' finished with non-zero exit value 128` on line 40 of the build.gradle file, and further down it says `Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0`, although i have 5.6.3 installed.

**Comment by wrongbaud** [comment]
I ended up using the following version, perhaps that will help you?

```
wrongbaud@wubuntu:~/blog/gauntlet-re$ gradle --version

------------------------------------------------------------
Gradle 5.6.3
------------------------------------------------------------

Build time:   2019-10-18 00:28:36 UTC
Revision:     bd168bbf5d152c479186a897f2cea494b7875d13

Kotlin:       1.3.41
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.14 compiled on March 12 2019
JVM:          11.0.2 (Oracle Corporation 11.0.2+9-LTS)
OS:           Linux 4.15.0-66-generic amd64

```

**Comment by Justin113D** [comment]
I basically have the same...
`------------------------------------------------------------
Gradle 5.6.3
------------------------------------------------------------

Build time:   2019-10-18 00:28:36 UTC
Revision:     bd168bbf5d152c479186a897f2cea494b7875d13

Kotlin:       1.3.41
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.14 compiled on March 12 2019
JVM:          11.0.4 (AdoptOpenJDK 11.0.4+11)
OS:           Windows 10 10.0 amd64`

**Comment by Justin113D** [comment]
Nevermind, i didnt know i needed to clone the repository through commandline! Thanks for the help ^^
Although, I think it'd be nice if all those things were mentioned in the readme :/
