### ISSUE TITLE
Unable to build on Windows 7

### ISSUE THREAD

**Issue by Zephiles** [Cuyler36/Ghidra-GameCube-Loader#20]
When running **gradlew.bat**, I get a ton of errors, starting with this:
> error: cannot find symbol
import ghidra.app.util.MemoryBlockUtils;

and also:
> Execution failed for task ':compileJava'.

The same thing happens when manually downloading Gradle version 5.6.3 and running **gradle** in the root directory. Running **gradle wrapper** reports that it built successfully, but it does not create a **dist** folder.

**Comment by Cuyler36** [comment]
Sounds like you've got a lower version of Ghidra set in your PATH variable. MemoryBlockUtils used to be a non-static class called MemoryBlockUtil in < 9.1. Try rebuilding again after confirming 9.1 is what GHIDRA_INSTALL_DIR is set to in your PATH.

**Comment by Zephiles** [comment]
Yes, I'm currently using 9.0.4. I'll report back after updating.

**Comment by Zephiles** [comment]
Alright, so now running **gradlew.bat** throws this error:
> Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
Caused by: java.lang.ClassNotFoundException: org.gradle.wrapper.GradleWrapperMai
n

Running **gradle** in the root directory works correctly though.

**Comment by Cuyler36** [comment]
It must have to do with the Gradle installation. Ghidra specs say that only Gradle 5.0 is supported for building. I have no issues when running gradlew.bat with Gradle 5.0. I'd try using 5.0 and seeing if the problem persists.

**Comment by Zephiles** [comment]
From what I'm seeing, **gradlew.bat** is supposed to manually download and use the version of Gradle specified in **\gradle\wrapper\gradle-wrapper.properties**, and the version specified there is 5.6.3. Also, I was using 5.3.1 beforehand without issues.

**Comment by Cuyler36** [comment]
My gradle-wrapper.properties lists 5.0 as the version to use
`distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-5.0-bin.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
`
Try rebuilding with the additional wrapper task I added to build.gradle

**Comment by Zephiles** [comment]
Alright, it builds correctly with **gradlew.bat** now.

**Comment by Cuyler36** [comment]
Great, thanks for testing it!
