### ISSUE TITLE
Templated types not being identified

### ISSUE THREAD

**Issue by magcius** [Cuyler36/Ghidra-GameCube-Loader#24]
Not sure if this is an issue with Ghidra or not, but it's common to see the template type of an argument get lost forever during translation. A great example of this with Nintendo games is the number of times TVec3\<float\>* simply gets turned into TVec3*. There's no great way to turn this dummy type into a typedef either, in my experience.

It would be nice for this to just work.

**Comment by magcius** [comment]
Thanks to the wonders of HTML, my example got eaten. I meant to write "A great example of this with Nintendo games is the number of times TVec3\<float\>* simply gets turned into TVec3*".

**Comment by Cuyler36** [comment]
Is it not fine that the function signature generated contains the template type? As an example:
```cpp
/* __thiscall JAISe::JAISeMgr_startID_(JAISoundID,
                                       JGeometry::TVec3<float> const *,
                                       JAIAudience *) */```

**Comment by magcius** [comment]
The issue is that Ghidra thinks that they are all `TVec3*`, for both short and float subtypes, and retyping everything is quite a lot of busywork.

**Comment by Cuyler36** [comment]
Well I suppose it'd be possible to modify the demangler to check for standard types in parameter templates and add those to the name.

**Comment by magcius** [comment]
I believe we already call `dataType.setTemplate` on the parameter itself, no? Does Ghidra not care about templates for the types? I'm not sure how it works.

**Comment by Cuyler36** [comment]
Ghidra doesn't care. The decompiler is only C-compliant (minus __thiscall calling convention), so it just throws out template information afaik. It's only used in the function signature. I made a small edit to not remove the template name from data types, but it's causing double templating for some reason.
