### ISSUE TITLE
Better support CodeWarrior gpr/fpr proglue/epilogue

### ISSUE THREAD

**Issue by magcius** [Cuyler36/Ghidra-GameCube-Loader#25]
CodeWarrior has a common optimization where it jumps to a common handler in the function prologue/epilogue to set up parts of the stack, and this confuses Ghidra quite a lot. You'll typically see a translation like:

```
uVar2 = FUN_12345678();
uVar3 = (uVar2 >> 0x20);
uVar4 = uVar2;
```

uVar3 is r3, uVar4 is r4. I don't know if something can be done on the Ghidra side to better support this pattern, but it would be nice.

**Comment by Cuyler36** [comment]
Are you referring to the _save__gpr & _rest__gpr methods? AFAIK there's no easy way to have Ghidra detect them automatically. I could write a module for the GC Analyzer to do so but it it'd be a bit slow. I tried using the Function ID plugin as well to create FID databases for various versions of the official SDK however that didn't work. The hash of the set__gpr and rest__gpr methods should be consistent across all SDK versions.

**Comment by magcius** [comment]
Yeah, I meant the _save__gpr / _rest__gpr methods. I just meant handling them better in general, but I since found that if you mark them as Inline manually, they basically disappear.
