### ISSUE TITLE
Is there any way to allow for finding references to addresses labelled as RAM addresses?

### ISSUE THREAD

**Issue by JillCrungus** [Cuyler36/Ghidra-GameCube-Loader#26]
Hi.
Since ver 1.1.0, the loader has had an analyser which can resolve references to RAM addresses in decompiles. This has been a tremendous help for reverse engineering and the code becomes a lot more readable after this is done.

There is one limitation however and that is that even after identifying and labelling an address, there's doesn't really seem to be any way to find all locations that work with that address. Ghidra's usual "Right click -> Show references to" functionalities don't work on these addresses, presumably because those parts of Ghidra don't really "understand" how to find them or something?

I have no idea if this is actually something that can be "fixed", I have a feeling it's something that a plugin like this can't really touch or modify in such a way to make it work, so I don't really expect much but I thought I'd ask if it's a possibility at all anyway since it'd be very useful to see functions that work with important variables in the game. Maybe there's some workaround I can use?

Thanks!

**Comment by Cuyler36** [comment]
The default power pc analyzer should be able to find most references to data already. Is the game you're reverse engineering without debug symbols? I don't think it can be made too much better without flagging false positives. The reason the analyzer works well is thanks to the known SDA/SDA2 register values that are obtained from the code.

**Comment by JillCrungus** [comment]
> The default power pc analyzer should be able to find most references to data already. Is the game you're reverse engineering without debug symbols? I don't think it can be made too much better without flagging false positives. The reason the analyzer works well is thanks to the known SDA/SDA2 register values that are obtained from the binary's code.

Yeah, no symbols for this game unfortunately.

The problem I'm talking about is basically this:

I run the analyser which correctly identifies the RAM addresses and labels them something along the lines `iRam80612614`.

I know this address is used to store the current level ID, so I label it as such:
![image](https://user-images.githubusercontent.com/32760843/70659594-5101e580-1c58-11ea-98f7-2f2c46bc972f.png)

But unfortunately, while this does allow me to easily identify this address in decompiled in the future, there doesn't seem to be any way to actively try to find all instances where it's used as Ghidra doesn't really recognise instances of it properly when using "Find all references". Like I said, I'm not sure this is something a plugin would be able to control.
![image](https://user-images.githubusercontent.com/32760843/70659742-9cb48f00-1c58-11ea-8da3-dc285f4873f5.png)

**Comment by Cuyler36** [comment]
If we assume that the level is part of some undefined struct, then it makes sense that there aren't many references to that. It's likely the game passes around a pointer to the structure instead of directly accessing the address in RAM. If that's the case then you'll have to define the structure and any functions that use it to get references to the struct members. Not much we can do here with an analyzer. Anything done with pointers isn't really something ghidra can figure out without user input. However if that is directly accessed by it's ram address and those references aren't showing up then there may be something wrong with the default PPC Analyzer.

**Comment by JillCrungus** [comment]
> If we assume that the level is part of some undefined struct, then it makes sense that there aren't many references to that. It's likely the game passes around a pointer to the structure instead of directly accessing the address in RAM. If that's the case then you'll have to define the structure and any functions that use it to get references to the struct members. Not much we can do here with an analyzer. Anything done with pointers isn't really something ghidra can figure out without user input. However if that is directly accessed by it's ram address and those references aren't showing up then there may be something wrong with the default PPC Analyzer.

Yeah, the level stuff will definitely be part of a struct but we're still putting together info to figure it out.

Aren't the `xRamXXXXXXXXX` in decompiles produced by the Gamecube/Wii Program Analyser and not by the default PPC analyzer? I've had no problem finding references to the default data locations from before running the GC/Wii analyser.

As a note, these don't work after setting up a struct either:
![image](https://user-images.githubusercontent.com/32760843/70661191-a68bc180-1c5b-11ea-8efd-9a16f053de83.png)
