### ISSUE TITLE
Cannot use symbol maps made by Dolphin

### ISSUE THREAD

**Issue by Zephiles** [Cuyler36/Ghidra-GameCube-Loader#3]
Upon opening a dol and selecting the symbol map to use for it, Ghidra throws this error:

> Symbol Loader: The memory map information couldn't be located. This symbol map cannot be loaded.

These symbol maps were made by taking the addresses from one version of the game and porting them to another, so the symbol map starts with the .text section, and may or may not have the other sections.

This format is also the same as the one that Dolphin uses when you use the Save Symbol Map option.

**Comment by Cuyler36** [comment]
I would suggest modifying the symbol map to follow the standard format. The dolphin maps for TTYD are missing the memory map information at the end of the file. Here's an example of what one looks like:
`Memory map:
                   Starting Size     File
                   address           Offset
            .init  80003100 000024d0 000001a0
            extab  800055d0 00000000 00002670
       extabindex  800055d0 00000000 00002670
            .text  800055e0 002b54fc 00002680
           .ctors  802baae0 00000004 002b7b80
           .dtors  802bab00 00000008 002b7ba0
          .rodata  802bab20 00044910 002b7bc0
            .data  802ff440 000c67dc 002fc4e0
             .bss  803c5c20 0004e0f0 003c2cc0
           .sdata  80413d20 00001434 003c2cc0
            .sbss  80415160 00000b98 003c4100
          .sdata2  80415d00 000087d4 003c4100
           .sbss2  8041e4e0 00000404 003cc8e0
   .debug_srcinfo           000000 00000000
   .debug_sfnames           000000 00000000
           .debug           000000 00000000
            .line           000000 00000000`

**Comment by Zephiles** [comment]
The problem with this is that the retail versions of TTYD do not have symbol maps on them, so we don't know most of that information.

This also doesn't get around the issue that Dolphin itself always creates the symbol maps the same way, in which that memory map layout is never used.

**Comment by Cuyler36** [comment]
[G8ME01.zip](https://github.com/Cuyler36/Ghidra-GameCube-Loader/files/3065586/G8ME01.zip)

**Comment by Zephiles** [comment]
It seems rather unnecessary to have to figure these out manually when Dolphin does all of this automatically. 

Also, the size of the .text section in the map you just uploaded is incorrect.

**Comment by Cuyler36** [comment]
The .text size isn't incorrect. I subtracted the .init section's size from it. The Dolphin map file had everything included in the .text section. Dolphin doesn't care about that, but it's technically incorrect.

To address your concern about why Dolphin maps aren't supported, it's due to how relocatable module maps are setup. Their symbol addresses are relative to the start of the section, so to support it the symbol map is absolutely required.

**Comment by Zephiles** [comment]
The thing is that the dol files should always be static, so there's really no reason to have requirements like that for them.

**Comment by Cuyler36** [comment]
The Symbol Loader doesn't know what type of binary it's loading. It only has one implementation. I'd have to add unnecessary logic to it to support Dolphin map files, or I'd have to create different symbol loader implementations for each binary type.

**Comment by Zephiles** [comment]
Considering that Dolphin map files are used quite often, I would imagine that being able to use them on the fly would be a good feature to have, even if they have to be handled separately.

**Comment by NWPlayer123** [comment]
> Considering that Dolphin map files are used quite often, I would imagine that being able to use them on the fly would be a good feature to have, even if they have to be handled separately.

Easy, fix Dolphin 😛

**Comment by Cuyler36** [comment]
Dolphin map files should load properly now. I hadn't realized how simple it was to add it until I checked haha.
