### ISSUE TITLE
Version Issue

### ISSUE THREAD

**Issue by octagonalsquare** [Cuyler36/Ghidra-GameCube-Loader#32]
Ghidra gives the following error when trying to install the extension:

"Extension version for [Ghidra-GameCube-Loader-master.zip] is incompatible with Ghidra"

I am not sure what to do about this. When looking in the "Install Extensions" window, this extension in red and has no version number.

**Comment by Cuyler36** [comment]
What version of Ghidra are you using? The latest release is only compiled for 9.1.
