### ISSUE TITLE
Windows run of gradlew fails with git issues

### ISSUE THREAD

**Issue by ikirkconnell** [Cuyler36/Ghidra-GameCube-Loader#33]
Correct JAVA_HOME value, running gradlew -PGHIDRA_INSTALL_DIR=<relevant Ghidra install directory> ends with "Process 'command 'git'' finished with non-zero exit value 128.

No zip generated. Any recommendations?

**Comment by Cuyler36** [comment]
Have you tried setting GHIDRA_INSTALL_DIR in your PATH?
