### ISSUE TITLE
[Question] Is this specifically GameCube dols? Does it support Wii dols as well?

### ISSUE THREAD

**Issue by ProfElements** [Cuyler36/Ghidra-GameCube-Loader#35]
I would like to use this to reverse engineering Wii games too, I dont know if it actually support that too.

**Comment by Cuyler36** [comment]
It technically works for Wii but it's meant for GameCube games. Any oddities with loading Wii executables will not be fixed.

**Comment by ProfElements** [comment]
Thank you
