### ISSUE TITLE
Feature Request: RSO Loading

### ISSUE THREAD

**Issue by Antidote** [Cuyler36/Ghidra-GameCube-Loader#36]
It'll be useful to be able to load RSO and .sel (codeless RSOs used to store symbols) files for Wii games since most of them use the RSO format instead of REL since it's a bit more powerful and flexible.

**Comment by Cuyler36** [comment]
Anything Wii related is not currently in-scope for this project. While the loader can load Wii binaries due to hardware and spec similarities between the GC and Wii, it's still a GameCube loader.

**Comment by Antidote** [comment]
I think that's a rather obtuse answer considering much of the REL code can be used, adding RSO support is barely much more than supporting a new container.

**Comment by Cuyler36** [comment]
I didn't say support wouldn't be added in the future but this was never planned to be a Wii loader. If I decide to formally support Wii binaries in the future (which I may), then I would definitely look into this. At the moment I don't have the time to dedicate to something like that.

**Comment by NWPlayer123** [comment]
> 
> 
> I think that's a rather obtuse answer considering much of the REL code can be used, adding RSO support is barely much more than supporting a new container.
> 
> On top of that, your lack of desire to support anything Wii related severely limits the usefulness of this loader.

The fork button is up in the right hand corner, Mr. It's-So-Easy
