### ISSUE TITLE
Separate the CodeWarriorDemangler into another plugin

### ISSUE THREAD

**Issue by astrelsky** [Cuyler36/Ghidra-GameCube-Loader#38]
It would be nice to have the CodeWarriorDemangler available as a separate plugin. It would become available by implementing [Demangler](https://ghidra.re/ghidra_docs/api/ghidra/app/util/demangler/Demangler.html) and [Demangler.canDemangle(Program)](https://ghidra.re/ghidra_docs/api/ghidra/app/util/demangler/Demangler.html#canDemangle(ghidra.program.model.listing.Program)) could simply be the following:
```java
@Override
public boolean canDemangle(Program program) {
    try {
        return program.getUsrPropertyManager().getVoidPropertyMap({INSERT_PUBLIC_STATIC_PROPERTY_NAME_HERE}) != null;
    } catch (TypeMismatchException e) {
        // not our property
        return false;
    }
}
```

The demangler class would need to have the `@ExtensionPointProperties(priority = 2)` annotation so that it will take priority over the builtin demanglers and be in use when someone adds the property to the program.

@lab313ru I never was able to get everything working in the demangler I was trying, but it turns out it exists somewhere. https://github.com/Cuyler36/Ghidra-GameCube-Loader/blob/7de775ed9814f08eebb34902a4c856a2fbe72893/src/main/java/gamecubeloader/common/SymbolLoader.java#L569

**Comment by Cuyler36** [comment]
You can now find the self contained demangler here: https://github.com/Cuyler36/CodeWarriorDemangler

**Comment by astrelsky** [comment]
> You can now find the self contained demangler here: https://github.com/Cuyler36/CodeWarriorDemangler

Thank you. I have some minor fixes that I will track down and submit.

**Comment by JayFoxRox** [comment]
Unfortunately the code is now duplicated in the separate repository and https://github.com/Cuyler36/Ghidra-GameCube-Loader/blob/master/src/main/java/gamecubeloader/common/CodeWarriorDemangler.java

I wish that this was more cleanly separated (2 potential options):

A. This repository could use the CodeWarriorDemangler repository as a submodule; CodeWarriorDemangler becomes single-source-of-truth, but is bundled with this plugin.
B. The CodeWarriorDemangler getting release-builds; CodeWarriorDemangler becomes single-source-of-truth, but is installed separately (similar to https://github.com/aldelaro5/ghidra-gekko-broadway-lang).

For context: I personally want to use this demangler with https://github.com/beardypig/ghidra-emotionengine, so I don't care how it is included in this project, as long as it's easy to use it in (or with) another extension.
A single-source-of-truth is important, so I can benefit from future changes / bugfixes / Ghidra version upgrades.
