### ISSUE TITLE
Overlapping symbols with dol + rel files

### ISSUE THREAD

**Issue by Zephiles** [Cuyler36/Ghidra-GameCube-Loader#4]
I've noticed that when opening both the dol and the rel files with their symbol maps, there seems to be some overlapping of symbols. I tested this with a demo version of TTYD, which has all of the symbol map files included. The end result is stuff like this:

![Overlapping](https://i.imgur.com/cOhS9qN.png)

The overlapping symbols appear to be coming from the _**.sbss2**_ section of the dol's symbol map file, but I can't be 100% sure.

**Comment by Cuyler36** [comment]
The issue appears to be with how TTYD's demo is set up. The sbss2 section overlaps into where the first module is loaded. I haven't encountered it elsewhere. I'm looking into the issue.

**Comment by Zephiles** [comment]
This exact same problem occurs with Twilight Princess's rel files as well, and their symbol maps use a different format.
