### ISSUE TITLE
Feature Request: RSO Modules

### ISSUE THREAD

**Issue by InusualZ** [Cuyler36/Ghidra-GameCube-Loader#42]
Loading RSO Modules could help with symbol resolution. 

Description from wiki
> The RSO format is the file format for shared objects for Wii games. This is essentially the Wii's equivalent of a DLL file, allowing for code modules to be dynamically linked at runtime and unlinked when not in use to save memory. It's very similar to the  GameCube's REL format, with the main difference being that the RSO format resolves symbol references via runtime symbol lookups rather than having pre-calculated offsets into the game's module files. 

[Specifications](http://www.metroid2002.com/retromodding/wiki/RSO_(File_Format))

**Comment by Cuyler36** [comment]
Closed by #51
