### ISSUE TITLE
Upgrade to Ghidra 9.2.3 and 9.2.4

### ISSUE THREAD

**Issue by JayFoxRox** [Cuyler36/Ghidra-GameCube-Loader#44]
Also see a similar request in https://github.com/beardypig/ghidra-emotionengine/issues/64 for another Ghidra plugin, and existing automated workflows in https://github.com/beardypig/ghidra-emotionengine/tree/master/.github/workflows

It might be possible to quickly add nightly-builds for this project, to avoid such requests.

I'd compile locally if I could, but my Linux distribution only ships the latest Gradle 7.x, which is incompatible with Ghidra 9.2.4 (which is also the only Ghidra version shipping with my Linux distribution).

**Comment by Pokechu22** [comment]
The extension has been updated for Ghidra 10.0 (and also Gradle 7.1).
