### ISSUE TITLE
Demangler broken in Ghidra 10.0.3

### ISSUE THREAD

**Issue by AlexApps99** [Cuyler36/Ghidra-GameCube-Loader#47]
I have tried this extension's demangler, and the separated code at https://github.com/Cuyler36/CodeWarriorDemangler/, and both seem to come up with an error when running `DemangleAllScript`, and don't do any demangling.

![image](https://user-images.githubusercontent.com/30854646/134765076-19c2a843-a5c2-4edb-b844-a878562b447c.png)

Deprecation error message, I only noticed this while building `CodeWarriorDemangler` and not `Ghidra-GameCube-Loader`
```
~/CodeWarriorDemangler/src/main/java/cwdemangler/CodeWarriorDemangler.java:453: warning: [removal] demangle(String,boolean) in Demangler has been deprecated and marked for removal
    public DemangledObject demangle(String mangled, boolean demangleOnlyKnownPatterns)
                           ^
1 warning
```

**Comment by Cuyler36** [comment]
The demangler isn't intended for use with ghidra script as is. From what I understand from the error message, it's missing some required extension entry point needed to run as a script.

**Comment by AlexApps99** [comment]
This also happens when you analyse

**Comment by Cuyler36** [comment]
Can you try now that https://github.com/Cuyler36/Ghidra-GameCube-Loader/commit/53bfd5297fac8606ea0aeff9719e79d129e4710b is merged?

**Comment by AlexApps99** [comment]
Yes, it seems to work now. Thanks!
