### ISSUE TITLE
Ghidra 10.1 rejects the latest version of this extension

### ISSUE THREAD

**Issue by Hallowizer** [Cuyler36/Ghidra-GameCube-Loader#49]
I'm probably doing something extremely stupid, but when attempting to install this extension, Ghidra shows the extension in red, and refuses to let me enable it.
<img width="702" alt="Screen Shot 2021-11-24 at 6 48 52 PM" src="https://user-images.githubusercontent.com/40325350/143371195-110e990e-46f7-4e86-9701-5bcd282f7e0c.png">

**Comment by Hallowizer** [comment]
Apparently it still works on older versions? I'm using v10.1

**Comment by modusc896d352** [comment]
the latest release was compiled with GHIDRA 10.0 in mind.
and yes it's that EXACT version.

**Comment by Cuyler36** [comment]
I released an updated build for [10.1](https://github.com/Cuyler36/Ghidra-GameCube-Loader/releases/tag/1.1.4).
