### ISSUE TITLE
10.1.1 Support

### ISSUE THREAD

**Issue by nununoisy** [Cuyler36/Ghidra-GameCube-Loader#50]
Extremely minor issue: Ghidra 10.1.1 was released not long ago. The only change is updating log4j to patch out the vulnerability.
I was able to edit the manifest in the extension to allow it to run and it is now working without issue, so I wanted to let you know so you can create a new release with the updated version.

**Comment by modusc896d352** [comment]
agreed.
trying to look at an Wii game executable on an outdated GHIDRA version is impractical at best and cumbersome at worst. i don't like to switch between multiple GHIDRA versions just to load one exe.

**Comment by Cuyler36** [comment]
Apologies for the time it took for a 10.1.1 compatible version. I don't follow Ghidra releases but I am usually notified within a few days when a release is published. You can find an updated extension [here](https://github.com/Cuyler36/Ghidra-GameCube-Loader/releases/tag/1.1.4_1).

**Comment by modusc896d352** [comment]
OK, the whole thing works now. thanks.
