### ISSUE TITLE
Ghidra 10.1.2

### ISSUE THREAD

**Issue by terorie** [Cuyler36/Ghidra-GameCube-Loader#53]
Could we get a GitHub Release with the plugin compiled against 10.1.2?

I've tested it locally and it works fine without any code changes.
Another pre-built plugin would useful for convenience since the latest release ZIP only works with Ghidra 10.1.1.

Thanks for your awesome plugin!

**Comment by EpochFlame** [comment]
likewise for 10.1.3

**Comment by HTV04** [comment]
Here's a build I compiled for 10.1.3: [GameCubeLoader-1.1.4-f8c20a7-Ghidra_10.1.3.zip](https://github.com/Cuyler36/Ghidra-GameCube-Loader/files/8693588/GameCubeLoader-1.1.4-f8c20a7-Ghidra_10.1.3.zip)

**Comment by GGLinnk** [comment]
> Here's a build I compiled for 10.1.3: [GameCubeLoader-1.1.4-f8c20a7-Ghidra_10.1.3.zip](https://github.com/Cuyler36/Ghidra-GameCube-Loader/files/8693588/GameCubeLoader-1.1.4-f8c20a7-Ghidra_10.1.3.zip)

There is something "wrong" with this build.
I don't know if this is critical but, as I said in #56, ``ppc_gekko_broadway.sla`` is missing from the source code and I don't know how this can impact the stability or the functionality of this extension.

**Comment by modusc896d352** [comment]
ghidra 10.1.4 has been released!

**Comment by ProfElements** [comment]
Ghidra 10.1.5 has been released :0 I would like a build pleas

**Comment by terorie** [comment]
Here's a build I completed earlier: <virus.jar> (Please don't run random JAR files from the comments :P) 

Will work on CI automation that automatically builds these against so we don't have to ping poor OP all the time heh

**Comment by HTV04** [comment]
> Here's a build I completed earlier: <virus.jar> (Please don't run random JAR files from the comments :P)

@terorie While this generally good advice, the 10.1.3 build I sent is not a virus. I built it against the 10.1.3 headers based on the instructions in the README. Just thought I'd share my build for those who couldn't compile it themselves.

I like the CI automation idea though, thanks for working on that!

**Comment by terorie** [comment]
> While this generally good advice, the 10.1.3 build I sent is not a virus. 

I believe you :) Better safe than sorry. PR here: https://github.com/Cuyler36/Ghidra-GameCube-Loader/pull/57 Anyone paranoid enough can use this on a fork to get builds for their own releases

The @doldecomp project kindly also created a fork where they will provide releases: https://github.com/doldecomp/Ghidra-GameCube-Loader
