### ISSUE TITLE
ppc_gekko_broadway.sla is present in releases...

### ISSUE THREAD

**Issue by GGLinnk** [Cuyler36/Ghidra-GameCube-Loader#56]
Hi,

I've finally understand why the .sla file was missing from custom build. Simply because it doesn't belongs here.
The .sla file should be generated by Ghidra on runtime and nothing else.

So the real issue finally is that this file shouldn't be in releases.

**Comment by encounter** [comment]
Thanks! Updated the latest release to exclude the .sla.
