### ISSUE TITLE
unable to disassemble stwu instruction

### ISSUE THREAD

**Issue by DacoTaco** [Cuyler36/Ghidra-GameCube-Loader#59]
I am currently looking at some System Menu stuff and i notice a few instructions being unable to be disassembled.
one of these is '94 21 FF F0    stwu r1, -0x10(r1)'
i got this one from shell-storm and verified it with dolphin.

i assume this requires an update in the language files?

it kinda blocks me from setting some code up as a function and check references

**Comment by SeekyCt** [comment]
That instruction disassembles completely fine for me, weird

**Comment by DacoTaco** [comment]
![image](https://user-images.githubusercontent.com/12701306/185753762-1f6596d2-28e6-4ab8-ac61-c600c3a290a8.png)
it refuses for me, very weird

**Comment by DacoTaco** [comment]
nvm, it mustve been the analyser fucking with it due to that align. fixed it

i feel ashamed haha
