### ISSUE TITLE
Error loading Dolphin Symbol Maps

### ISSUE THREAD

**Issue by Zephiles** [Cuyler36/Ghidra-GameCube-Loader#7]
This seems to be an issue with some of the newer updates, sometime after commit 91ff06fa6b633a379d5e3c2337099586f487cd7b. With TTYD, symbol maps in the Dolphin format are unable to load, but the ones from the demo disc seem to load perfectly fine.

This is one of the messages in the log when attempting to use a Dolphin symbol map:

> (SymbolLoader) Symbol Loader: The memory map information couldn't be located. This symbol map may not be loaded correctly.

Interestingly, the Twilight Princess symbol maps seem to load perfectly fine as well (at least, up to the point where issue #5 occurs), despite using a similar format.

**Comment by Cuyler36** [comment]
That commit should fix the issue. I'm leaving this open until the resolution has been confirmed.

**Comment by Zephiles** [comment]
Ya, that commit fixed the issue.
