### ISSUE TITLE
Feature Request: Add Support for RAM dumps

### ISSUE THREAD

**Issue by Zephiles** [Cuyler36/Ghidra-GameCube-Loader#8]
Under some instances, it can be useful to view the code inside of a RAM dump, while also being able to use a symbol map with it. The most common use of this would be from a Dolphin RAM dump, which dumps it into a .raw file.

**Comment by Cuyler36** [comment]
Support for loading RAM dumps (MEM1/GC Main RAM only) added in https://github.com/Cuyler36/Ghidra-GameCube-Loader/commit/05c0531359ca3a238992f92550104b1039addb27
