### ISSUE TITLE
Include gradle wrapper

### ISSUE THREAD

**Issue by chc4** [Cuyler36/Ghidra-GameCube-Loader#9]
The readme mentions that you can build via `./gradlew`. There isn't a gradle wrapper checked in, however, so that fails, and you instead have to install gradle locally and run it standalone.

**Comment by oddMLan** [comment]
NOT fixed
upon running gradlew you get presented with this error
```
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
Caused by: java.lang.ClassNotFoundException: org.gradle.wrapper.GradleWrapperMain
```
I noticed your gitignore has .jar files in it. you need to remove that from the gitignore so that gradle-wrapper.jar is included
